#!/bin/sh
set -eu

TAG=$(git describe --tags --dirty --always)
DATE=$(date -u)
VERSION="${TAG} [${DATE}]"
LDFLAGS="-s -w -X \"main.Version=${VERSION}\""

DEVBUDDY_PLATFORMS=${DEVBUDDY_PLATFORMS:-"linux darwin"}


for OS in ${DEVBUDDY_PLATFORMS[@]}; do
	NAME=bud-${OS}-amd64

	echo "Building $NAME"
	GOOS=${OS} GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags "$LDFLAGS" -o dist/${NAME}

	cd dist
	shasum -a 256 ${NAME} > ${NAME}.sha256
	cd ..
done
